
const productsDB = [
    {
        id: 1,
        titulo: 'Doom Eternal',
        precio: 500,
        rutaImagen: "/img/covers/cover_doom_eternal.jpg",
        category: "accion",
        descripcion: "alto juego",
    },
    {
        id: 2,
        titulo: 'Journey',
        precio: 300,
        rutaImagen: "/img/covers/cover_journey.jpg",
        category: "aventura",
        descripcion: "tremendo juego",
    },
    {
        id: 3,
        titulo: 'Hollow Knight',
        precio: 600,
        rutaImagen: "/img/covers/cover_hollow_knight.jpg",
        descripcion: "super juego",
    },
    {
        id: 4,
        titulo: 'Titanfall 2',
        precio: 247,
        rutaImagen: "/img/covers/cover_titanfall2.jpg",
        category: "accion",
        descripcion: "gran juego",
    },
    {
        id: 5,
        titulo: 'Divinity: Original Sin 2',
        precio: 247,
        rutaImagen: "/img/covers/cover_divinity_original_sin_2.jpg",
        category: "rpg",
        descripcion: "gran juego",
    },
    {
        id: 6,
        titulo: 'Alien Isolation',
        precio: 247,
        rutaImagen: "/img/covers/cover_alien_isolation.jpg",
        category: "accion", 
        descripcion: "gran juego",
    },
    {
        id: 7,
        titulo: 'Disco Elysium',
        precio: 247,
        rutaImagen: "/img/covers/cover_disco_elysium.jpg",
        category: "rpg",
        descripcion: "gran juego",
    },
    {
        id: 8,
        titulo: 'Final Fantasy XIV',
        precio: 247,
        rutaImagen: "/img/covers/cover_final_fantasy_xiv.jpg",
        category: "rpg",
        descripcion: "gran juego",
    },
    {
        id: 9,
        titulo: 'Outer Wilds',
        precio: 247,
        rutaImagen: "/img/covers/cover_outer_wilds.jpg",
        category: "aventura",
        descripcion: "gran juego",
    },
    {
        id: 10,
        titulo: 'Rainbow Six Siege',
        precio: 247,
        rutaImagen: "/img/covers/cover_rainbow_six_siege.jpg",
        category: "accion",
        descripcion: "gran juego",
    },
]

export default productsDB

